export const products = [
  {
    id: 1,
    image: "/blue-moto.png",
    product_name: "Blue Motorcycle",
    collection_name: "Motorcycles",
    price: 15000,
    old_price: 20000,
    colors: [
      { color_code: "#0043B7FF" },
      { color_code: "#8000F8FF" },
      { color_code: "#D91717FF" },
      { color_code: "#FFD418FF" },
    ],
  },
  {
    id: 2,
    image: "/purple-moto-helmet.png",
    product_name: "Purple Motorcycle Helmet",
    collection_name: "Helmets",
    price: 150,
    old_price: 200,
    colors: [
      { color_code: "#0061E8FF" },
      { color_code: "#8900ECFF" },
      { color_code: "#E3000CFF" },
    ],
  },
  {
    id: 3,
    image: "/yellow-moto.png",
    product_name: "Yellow Motorcycle",
    collection_name: "Motorcycles",
    price: 15000,
    old_price: 20000,
    colors: [
      { color_code: "#0043B7FF" },
      { color_code: "#8000F8FF" },
      { color_code: "#D91717FF" },
      { color_code: "#FFD418FF" },
    ],
  },
  {
    id: 4,
    image: "/red-moto-helmet.png",
    product_name: "Red Motorcycle Helmet",
    collection_name: "Helmets",
    price: 150,
    old_price: 200,
    colors: [
      { color_code: "#0061E8FF" },
      { color_code: "#8900ECFF" },
      { color_code: "#E3000CFF" },
    ],
  },
];
